from django.core.management.base import BaseCommand
from apps.users.models import Badge

class Command(BaseCommand):
    help = 'Seed all updated badges into the database'

    def handle(self, *args, **options):
        badges_data = [
            # ===== Streak Badges (1-8) =====
            {"badge_id": 1, "name": "First Spark", "category": "Streak", "rarity": "COMMON",
             "cloudinary_filename": "01_first_spark.jpeg",
             "requirement": "Maintain a 3-day quiz streak.",
             "description": "3-day streak"},
            {"badge_id": 2, "name": "Warming Up", "category": "Streak", "rarity": "COMMON",
             "cloudinary_filename": "02_warming_up.jpeg",
             "requirement": "Maintain a 7-day quiz streak.",
             "description": "7-day streak"},
            {"badge_id": 3, "name": "On Fire", "category": "Streak", "rarity": "RARE",
             "cloudinary_filename": "03_on_fire.jpeg",
             "requirement": "Maintain a 14-day quiz streak.",
             "description": "14-day streak"},
            {"badge_id": 4, "name": "Unstoppable", "category": "Streak", "rarity": "EPIC",
             "cloudinary_filename": "04_unstoppable.jpeg",
             "requirement": "Maintain a 30-day quiz streak.",
             "description": "30-day streak"},
            {"badge_id": 5, "name": "Iron Will", "category": "Streak", "rarity": "LEGENDARY",
             "cloudinary_filename": "05_iron_will.jpeg",
             "requirement": "Maintain a 60-day quiz streak.",
             "description": "60-day streak"},
            {"badge_id": 6, "name": "Legend", "category": "Streak", "rarity": "LEGENDARY",
             "cloudinary_filename": "06_legend.jpeg",
             "requirement": "Maintain a 100-day quiz streak.",
             "description": "100-day streak"},
            {"badge_id": 7, "name": "Immortal", "category": "Streak", "rarity": "LEGENDARY",
             "cloudinary_filename": "07_immortal.jpeg",
             "requirement": "Maintain a 365-day quiz streak.",
             "description": "365-day streak"},
            {"badge_id": 8, "name": "Comeback King", "category": "Streak", "rarity": "EPIC",
             "cloudinary_filename": "08_comeback_king.jpeg",
             "requirement": "Rebuild your streak after losing a 30+ day streak.",
             "description": "Rebuild after 30+ day streak loss"},

            # ===== Quiz Count Badges (9-16) =====
            {"badge_id": 9, "name": "First Step", "category": "Quiz Count", "rarity": "COMMON",
             "cloudinary_filename": "09_first_step.jpeg",
             "requirement": "Complete your first quiz.",
             "description": "Complete 1 quiz"},
            {"badge_id": 10, "name": "Beginner", "category": "Quiz Count", "rarity": "COMMON",
             "cloudinary_filename": "10_beginner.jpeg",
             "requirement": "Complete 10 quizzes.",
             "description": "10 quizzes"},
            {"badge_id": 11, "name": "Bookworm", "category": "Quiz Count", "rarity": "RARE",
             "cloudinary_filename": "11_bookworm.jpeg",
             "requirement": "Complete 50 quizzes.",
             "description": "50 quizzes"},
            {"badge_id": 12, "name": "Scholar", "category": "Quiz Count", "rarity": "EPIC",
             "cloudinary_filename": "12_scholar.jpeg",
             "requirement": "Complete 100 quizzes.",
             "description": "100 quizzes"},
            {"badge_id": 13, "name": "Quiz Machine", "category": "Quiz Count", "rarity": "EPIC",
             "cloudinary_filename": "13_quiz_machine.jpeg",
             "requirement": "Complete 250 quizzes.",
             "description": "250 quizzes"},
            {"badge_id": 14, "name": "Century Club", "category": "Quiz Count", "rarity": "RARE",
             "cloudinary_filename": "14_century_club.jpeg",
             "requirement": "Answer 100 questions in a single day.",
             "description": "100 questions in one day"},
            {"badge_id": 15, "name": "Marathoner", "category": "Quiz Count", "rarity": "RARE",
             "cloudinary_filename": "15_marathoner.jpeg",
             "requirement": "Complete 5 quizzes in a single day.",
             "description": "5 quizzes in one day"},
            {"badge_id": 16, "name": "Grandmaster", "category": "Quiz Count", "rarity": "LEGENDARY",
             "cloudinary_filename": "16_grandmaster.jpeg",
             "requirement": "Complete 500 quizzes.",
             "description": "500 quizzes"},

            # ===== Accuracy Badges (17-22) =====
            {"badge_id": 17, "name": "Sharp Shooter", "category": "Accuracy", "rarity": "RARE",
             "cloudinary_filename": "17_sharp_shooter.jpeg",
             "requirement": "Score 90% or higher in a quiz with at least 10 questions.",
             "description": "90%+ on 10+ questions"},
            {"badge_id": 18, "name": "Perfectionist", "category": "Accuracy", "rarity": "EPIC",
             "cloudinary_filename": "18_perfectionist.jpeg",
             "requirement": "Score 100% on any quiz (min 5 questions).",
             "description": "100% on 5-question quiz"},
            {"badge_id": 19, "name": "Flawless Five", "category": "Accuracy", "rarity": "LEGENDARY",
             "cloudinary_filename": "19_flawless_five.jpeg",
             "requirement": "Achieve 10 back-to-back perfect scores (100%).",
             "description": "10 consecutive 100% scores"},
            {"badge_id": 20, "name": "Consistent Mind", "category": "Accuracy", "rarity": "EPIC",
             "cloudinary_filename": "20_consistent_mind.jpeg",
             "requirement": "Maintain 80%+ average accuracy over your last 20 quiz attempts.",
             "description": "80%+ avg over last 20 attempts"},
            {"badge_id": 21, "name": "No Mistakes Allowed", "category": "Accuracy", "rarity": "EPIC",
             "cloudinary_filename": "21_no_mistakes.jpeg",
             "requirement": "Complete 3 quizzes in a row without a single incorrect answer.",
             "description": "3 quizzes with no incorrect answers"},
            {"badge_id": 22, "name": "Redemption Arc", "category": "Accuracy", "rarity": "RARE",
             "cloudinary_filename": "22_redemption_arc.jpeg",
             "requirement": "Score 100% on a quiz you previously failed.",
             "description": "100% on a previously failed quiz"},

            # ===== Subject Badges (27-33) =====
            {"badge_id": 27, "name": "Code Conqueror", "category": "Subject", "rarity": "RARE",
             "cloudinary_filename": "27_code_conqueror.jpeg",
             "requirement": "Master 5 Coding quizzes (score 80%+ each).",
             "description": "5 Coding quizzes mastered"},
            {"badge_id": 28, "name": "Python Pro", "category": "Subject", "rarity": "RARE",
             "cloudinary_filename": "28_python_pro.jpeg",
             "requirement": "Master 5 Python quizzes (score 80%+ each).",
             "description": "5 Python quizzes mastered"},
            {"badge_id": 29, "name": "Java Genius", "category": "Subject", "rarity": "EPIC",
             "cloudinary_filename": "29_java_genius.jpeg",
             "requirement": "Master 5 Java quizzes (score 80%+ each).",
             "description": "5 Java quizzes mastered"},
            {"badge_id": 30, "name": "C++ Champion", "category": "Subject", "rarity": "RARE",
             "cloudinary_filename": "30_cpp_champion.jpeg",
             "requirement": "Master 5 C++ quizzes (score 80%+ each).",
             "description": "5 C++ quizzes mastered"},
            {"badge_id": 32, "name": "All-Rounder", "category": "Subject", "rarity": "EPIC",
             "cloudinary_filename": "32_all_rounder.jpeg",
             "requirement": "Score 80%+ in 5 different subjects.",
             "description": "80%+ in 5 subjects"},
            {"badge_id": 33, "name": "Subject Master", "category": "Subject", "rarity": "LEGENDARY",
             "cloudinary_filename": "33_subject_master.jpeg",
             "requirement": "Master 10 subjects (score 80%+ each).",
             "description": "10 subjects mastered"},

            # ===== Time & Dedication Badges (34-39) =====
            {"badge_id": 34, "name": "Daily Dedication", "category": "Time", "rarity": "COMMON",
             "cloudinary_filename": "34_daily_dedication.jpeg",
             "requirement": "Complete a quiz every day for 7 consecutive days.",
             "description": "7 days of daily quiz"},
            {"badge_id": 35, "name": "Time Keeper", "category": "Time", "rarity": "RARE",
             "cloudinary_filename": "35_time_keeper.jpeg",
             "requirement": "Spend 60 minutes learning (taking quizzes) in a single day.",
             "description": "60 minutes in one day"},
            {"badge_id": 37, "name": "Early Bird", "category": "Time", "rarity": "RARE",
             "cloudinary_filename": "37_early_bird.jpeg",
             "requirement": "Complete a quiz before 9 AM.",
             "description": "Quiz before 9 AM"},
            {"badge_id": 38, "name": "Night Owl", "category": "Time", "rarity": "RARE",
             "cloudinary_filename": "38_night_owl.jpeg",
             "requirement": "Complete a quiz after 10 PM.",
             "description": "Quiz after 10 PM"},
            {"badge_id": 39, "name": "Goal Getter", "category": "Time", "rarity": "EPIC",
             "cloudinary_filename": "39_goal_getter.jpeg",
             "requirement": "Achieve today's quiz goal 7 times.",
             "description": "7 times achieving daily goal"},

            # ===== Miscellaneous Badges (40, 45, 50-64) =====
            {"badge_id": 40, "name": "Explorer", "category": "Miscellaneous", "rarity": "COMMON",
             "cloudinary_filename": "40_explorer.jpeg",
             "requirement": "Attempt quizzes from 5 different subjects.",
             "description": "5 different subjects attempted"},
            {"badge_id": 45, "name": "Hidden Gem", "category": "Miscellaneous", "rarity": "LEGENDARY",
             "cloudinary_filename": "45_hidden_gem.jpeg",
             "requirement": "Find and complete a quiz with less than 2 attempts by others.",
             "description": "Complete a rarely attempted quiz"},
            {"badge_id": 50, "name": "Risk Taker", "category": "Miscellaneous", "rarity": "RARE",
             "cloudinary_filename": "50_risk_taker.jpeg",
             "requirement": "Attempt a Hard difficulty quiz and score 70%+.",
             "description": "70%+ on Hard quiz"},
            {"badge_id": 51, "name": "Weekly Warrior", "category": "Miscellaneous", "rarity": "EPIC",
             "cloudinary_filename": "51_weekly_warrior.jpeg",
             "requirement": "Complete 20 quizzes in a week.",
             "description": "20 quizzes in a week"},
            {"badge_id": 52, "name": "Analyst", "category": "Miscellaneous", "rarity": "RARE",
             "cloudinary_filename": "52_analyst.jpeg",
             "requirement": "Review answers of 20 questions (use review page).",
             "description": "20 reviewed answers"},
            {"badge_id": 53, "name": "Top Performer", "category": "Leaderboard", "rarity": "LEGENDARY",
             "cloudinary_filename": "53_top_performer.jpeg",
             "requirement": "Reach the Top 10 on the global leaderboard.",
             "description": "Top 10 leaderboard"},
            {"badge_id": 54, "name": "Quiz Champion", "category": "Quiz Count", "rarity": "LEGENDARY",
             "cloudinary_filename": "54_quiz_champion.jpeg",
             "requirement": "Win 100 quizzes (score 80%+ each).",
             "description": "100 quizzes with 80%+ score"},
            {"badge_id": 55, "name": "Milestone Maker", "category": "Quiz Count", "rarity": "EPIC",
             "cloudinary_filename": "55_milestone_maker.jpeg",
             "requirement": "Complete 50 quizzes.",
             "description": "50 quizzes"},
            {"badge_id": 58, "name": "Knowledge Seeker", "category": "Miscellaneous", "rarity": "EPIC",
             "cloudinary_filename": "58_knowledge_seeker.jpeg",
             "requirement": "Attempt quizzes from 10 different subjects.",
             "description": "10 different subjects attempted"},
            {"badge_id": 59, "name": "Peak Performer", "category": "Accuracy", "rarity": "RARE",
             "cloudinary_filename": "59_peak_performer.jpeg",
             "requirement": "Score 95% or more in a quiz (min 10 Qs).",
             "description": "95%+ on 10+ Qs"},
            {"badge_id": 60, "name": "Precision Master", "category": "Accuracy", "rarity": "EPIC",
             "cloudinary_filename": "60_precision_master.jpeg",
             "requirement": "Answer 100 questions correctly in total.",
             "description": "100 correct answers"},
            {"badge_id": 61, "name": "Speed Runner", "category": "Time", "rarity": "RARE",
             "cloudinary_filename": "61_speed_runner.jpeg",
             "requirement": "Complete a quiz in half the given time.",
             "description": "Complete in <50% of time"},
            {"badge_id": 62, "name": "Legend in Progress", "category": "Leaderboard", "rarity": "LEGENDARY",
             "cloudinary_filename": "62_legend_in_progress.jpeg",
             "requirement": "Reach Rank 1 on the global leaderboard.",
             "description": "Rank 1 on leaderboard"},
            {"badge_id": 64, "name": "Feedback Hero", "category": "Miscellaneous", "rarity": "EPIC",
             "cloudinary_filename": "64_feedback_hero.jpeg",
             "requirement": "Give feedback to help improve the platform.",
             "description": "Submit feedback"},
        ]

        for badge in badges_data:
            obj, created = Badge.objects.get_or_create(
                badge_id=badge['badge_id'],
                defaults={
                    'name': badge['name'],
                    'description': badge['description'],
                    'image_url': f"https://res.cloudinary.com/your-cloud/badges/{badge['cloudinary_filename']}",
                    'cloudinary_filename': badge['cloudinary_filename'],
                    'requirement': badge['requirement'],
                    'category': badge['category'],
                    'rarity': badge['rarity'],
                }
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"✅ Created: {badge['name']}"))
            else:
                self.stdout.write(f"ℹ️ Already exists: {badge['name']}")

        self.stdout.write(self.style.SUCCESS("\n🎉 All updated badges seeded successfully!"))