# Generated by Django 6.0.6 on 2026-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quizzes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
