# Generated by Django 6.0.6 on 2026-07-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_streak_user_last_active_date_and_more'),
    ]

    operations = [
    ]
