# Generated by Django 6.0.6 on 2026-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_level_user_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbadge',
            old_name='awarded_at',
            new_name='earned_at',
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='status',
            field=models.CharField(choices=[('CLAIMABLE', 'Claimable'), ('CLAIMED', 'Claimed')], default='CLAIMABLE', max_length=20),
        ),
    ]
