# Generated by Django

from django.db import migrations
from django.contrib.auth.hashers import make_password

def ensure_superuser(apps, schema_editor):
    User = apps.get_model('users', 'User')
    try:
        user = User.objects.get(email='admin@test.com')
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.role = 'Admin'
        user.save()
    except User.DoesNotExist:
        # Check if username 'admin' already exists
        try:
            user = User.objects.get(username='admin')
            user.email = 'admin@test.com'
            user.is_staff = True
            user.is_superuser = True
            user.is_active = True
            user.role = 'Admin'
            user.save()
        except User.DoesNotExist:
            User.objects.create(
                username='admin',
                email='admin@test.com',
                password=make_password('admin123', hasher='pbkdf2_sha256'),
                is_staff=True,
                is_superuser=True,
                is_active=True,
                role='Admin'
            )

def reverse_ensure(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        # Updated to match your actual last migration file
        ('users', '0005_rename_awarded_at_userbadge_earned_at_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_superuser, reverse_ensure),
    ]