# Generated by Django 6.0.6 on 2026-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ensure_superuser'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'status'], name='users_userb_user_id_ef89bb_idx'),
        ),
    ]
