# Generated by Django 6.0.6 on 2026-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('True/False', 'True/False'), ('Fill in the Blank', 'Fill in the Blank'), ('Coding', 'Coding')], max_length=50),
        ),
    ]
