# Generated by Django 6.0.6 on 2026-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('True/False', 'True/False'), ('Fill in the Blank', 'Fill in the Blank')], max_length=50)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('total_marks', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('join_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('share_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
