# Generated by Django 6.0.6 on 2026-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_grade_level_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
