# Generated by Django 6.0.6 on 2026-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_created_at_alter_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
