# Generated by Django 6.0.6 on 2026-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
