# Generated by Django 6.0.6 on 2026-07-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_quizattempt_time_spent_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
