# Generated by Django 6.0.6 on 2026-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_useranswer_marked_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
