# Generated by Django 6.0.6 on 2026-07-21 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0006_useranswer_reviewed'),
        ('quizzes', '0004_quiz_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'submitted_at'], name='attempts_qu_user_id_02028b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'submitted_at'], name='attempts_qu_quiz_id_5a0b03_idx'),
        ),
    ]
