# Generated by Django 6.0.6 on 2026-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0007_quizattempt_is_auto_submitted_and_more'),
        ('questions', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='attempts_us_attempt_6d97a7_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='attempts_us_questio_61b50c_idx'),
        ),
    ]
