# Generated by Django 6.0.6 on 2026-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Login', 'Login'), ('Password Reset', 'Password Reset'), ('Email Verification', 'Email Verification')], max_length=50),
        ),
    ]
